[system] Add stack overflow test
Details

  This change introduces a new test module that invokes a recursive
  function that will overflow the stack and cause a hardware fault.
  Because the hardware fault is not handled, the system exits.

  In addition to this new test module, a new 'skl-test-system' script
  is added to run these types of tests.

Testing

  With an alpha build:

    The alpha build style performs more checking and fails with a more
    descriptive message written to the console indicating that the
    interpreter has found an issue with the code being executed.  A
    future change will clean this fatal error up so that the hardware
    trap is properly delivered.

    ./scripts/skl-test-system
    Executing: skl-skl-oc /nas/homes/thutt/skl/skl-o2/system/lms/tests/StackOverflow.Mod
    Executing: skl-oberon StackOverflow.Test
    Heap beg [0x4000000]  0x3ffffe0  bad
    Heap end [0x8200000]  0x3ffffe0  good

fatal error: validate_heap_pointer: Pointer not inside heap.

  With a release build:

    ./scripts/skl-test-system

    Successful termination due to hardware trap.