[CommandLine.Mod] Fix trailing whitespace causing array index errors
Details

  If the command line had trailing whitespace, an additional call to
  ParseNexParm() would be made.  This call would find there are no
  additional parameters and return a value for the next index that
  would violate the invariant conditions of the function.

  To prevent this from happening, now whitespace following each
  argument is consumed, so that the return value will either be the
  end of the command line, or the exact start of the next argument.

Testing

  Ad hoc testing with this command line:

    skl-skl-oc

  Prior to this fix, the following backtrace would be shown:

    abnormal program termination
    TRAP code=13 (array index)
         pc=392202A4 (CommandLine, offset=00000144) sfp=391FFFDC
    CommandLine.Parse [000000C0H..00000164H)
       NextOffset[-4] =  -2
       i[-2] =  -2
    CommandLine.Init [00000024H..000000C0H)
       root[-4] = 3922A830H
    CommandLine.CommandLine [00000000H..00000024H)
       ParameterCount[-2] = 14626
       parmlist[-4104] = 00000000H
    Kernel.BootstrapModuleInit [0000028CH..000002C0H)

    fatal error: Hardware trap raised while processing hardware trap.