[scripts] Whitespace cleanup, and address failures on MacOS
Details

  An extra blank line between functions is removed in
  skl-module-test-harness.py for consistency.

  Next, MacOS running ct-test-compiler will sometimes fail with the
  following backtrace:

     *** Executing: 'CTInvalidOpcode'
      Traceback (most recent call last):
        File "/Users/thutt/oberon/scripts/skl-module-test-harness.py", line 634, in <module>
          sys.exit(main())
        File "/Users/thutt/oberon/scripts/skl-module-test-harness.py", line 630, in main
          perform_test(options, test_definitions, "compiler")
        File "/Users/thutt/oberon/scripts/skl-module-test-harness.py", line 608, in perform_test
          test_module(options, test)
        File "/Users/thutt/oberon/scripts/skl-module-test-harness.py", line 587, in test_module
          (stdout, stderr, rc) = execute_oberon(options,
        File "/Users/thutt/oberon/scripts/skl-module-test-harness.py", line 543, in execute_oberon
          (stdout, stderr, rc) = execute.process(cmd)
        File "/Users/thutt/oberon/scripts/execute.py", line 22, in process
          stdout = stdout.decode("UTF-8")
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 643: invalid start byte

   Adding 'errors="backslashreplace"' to the decoding of each line of
   stdout and stderr in execute.process() causes the error to not
   occur.

Testing

  In 10 runs of the compiler test suite, the error has not happened.