[SKL] Allow GSA documentation to be fully viewed in xdvi
Details

  There is a deleterious interaction between LaTex / TeX and
  Ghostscript that causes xdvi (which uses Ghostscript) to output
  errors like the following on the console when encountering
  MetaPost-generated content while using xdvi:

    Error: /undefined in cmr10

  This page does not provide too many details:

    https://texfaq.org/FAQ-mpprologues

  but it is sufficient to dictate adding 'prologues := 2' to MetaPost
  files.

  This change updates the MetaPost files, where necessary to allow the
  graphics from within xdvi.  However, the xdvi being used for this
  project:

    xdvik version 22.87 (Xaw toolkit)
    Libraries: kpathsea version 6.2.1, freetype version 2.5.5

  does not clear the GhostScript regions when switching between pages,
  and the images will eventually begin to look like a frenetic
  Etch-A-Sketch.  The solution for this encumbrance is to quit xdvi,
  reload the document and navigate directly to the desired page.

Testing

  skl-build -j 10
  skl-list-documentation
  xdvi /tmp/skl/skl-o2/release/doc/gsa/gsa.dvi